-include ../../../header.mk

SRC := dma/dma.cpp \
	exti/exti.cpp \
	gpio/gpio.cpp \
	rcc/rcc.cpp \
	systick/systick.cpp \
	tim/tim.cpp \
	wdt/wdt.cpp

INC :=

DEF :=
C_CPP_FLAGS := -Wno-unused-variable
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../../footer.mk
