-include ../../../header.mk

SRC := dma.cpp \
	exti.cpp \
	gpio.cpp \
	rcc.cpp \
	systick.cpp \
	tim.cpp \
	wdt.cpp

INC :=

DEF :=
C_CPP_FLAGS := -Wno-unused-variable
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../../footer.mk
