SRC += hal/STM32F0/CMSIS/device-support/startup_stm32f072xb.s
SRC += hal/STM32F0/CMSIS/device-support/system_stm32f0xx.c
SRC += hal/STM32F0/CMSIS/syscalls.c
SRC += hal/STM32F0/CMSIS/sys.c
SRC += hal/STM32F0/dma.cpp
SRC += hal/STM32F0/exti.cpp
SRC += hal/STM32F0/gpio.cpp
SRC += hal/STM32F0/rcc.cpp
SRC += hal/STM32F0/systick.cpp
SRC += hal/STM32F0/tim.cpp
SRC += hal/STM32F0/wdt.cpp

INC += src/hal/STM32F0
INC += src/hal/STM32F0/CMSIS/core-support
INC += src/hal/STM32F0/CMSIS/device-support/include

DEF += STM32F072xB
DEF += HSE_VALUE=8000000
DEF += ARM_MATH_CM0

LIBDIR += src/hal/STM32F0/CMSIS/lib
LIB += arm_cortexM0l_math
LINKED_OBJ +=
