SRC += hal/STM32F1/CMSIS/device-support/startup_stm32f100xb.s
SRC += hal/STM32F1/CMSIS/device-support/system_stm32f1xx.c
SRC += hal/STM32F1/CMSIS/syscalls.c
SRC += hal/STM32F1/CMSIS/sys.c
SRC += hal/STM32F1/dac.cpp
SRC += hal/STM32F1/dma.cpp
SRC += hal/STM32F1/exti.cpp
SRC += hal/STM32F1/gpio.cpp
SRC += hal/STM32F1/pwm.cpp
SRC += hal/STM32F1/rcc.cpp
SRC += hal/STM32F1/systick.cpp
SRC += hal/STM32F1/tim.cpp
SRC += hal/STM32F1/uart.cpp
SRC += hal/STM32F1/wdt.cpp

INC += src/hal/STM32F1
INC += src/hal/STM32F1/CMSIS/core-support
INC += src/hal/STM32F1/CMSIS/device-support/include

DEF += STM32F100xB
DEF += HSE_VALUE=8000000
DEF += ARM_MATH_CM3

LIBDIR += src/hal/STM32F1/CMSIS/lib
LIB += arm_cortexM3l_math
LINKED_OBJ +=
