-include ../../../header.mk

SRC := adc/adc.cpp \
	dac/dac.cpp \
	dma/dma.cpp \
	exti/exti.cpp \
	gpio/gpio.cpp \
	pwm/pwm.cpp \
	rcc/rcc.cpp \
	systick/systick.cpp \
	tim/tim.cpp \
	uart/uart.cpp \
	wdt/wdt.cpp

INC :=

DEF :=
C_CPP_FLAGS := -Wno-unused-variable
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../../footer.mk
