-include ../../header.mk

SRC := fatfs_diskio/fatfs_diskio.cpp \
	fatfs_diskio/fatfs_diskio_sd.cpp \
	syslog/syslog.cpp

INC :=
DEF :=
C_CPP_FLAGS :=
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../footer.mk
