SRC += hal/STM32F4/CMSIS/device-support/startup_stm32f407xx.s
SRC += hal/STM32F4/CMSIS/device-support/system_stm32f4xx.c
SRC += hal/STM32F4/CMSIS/syscalls.c
SRC += hal/STM32F4/CMSIS/sys.c
SRC += hal/STM32F4/dac.cpp
SRC += hal/STM32F4/dma.cpp
SRC += hal/STM32F4/exti.cpp
SRC += hal/STM32F4/gpio.cpp
SRC += hal/STM32F4/i2c.cpp
SRC += hal/STM32F4/pwm.cpp
SRC += hal/STM32F4/rcc.cpp
SRC += hal/STM32F4/rtc.cpp
SRC += hal/STM32F4/spi.cpp
SRC += hal/STM32F4/systick.cpp
SRC += hal/STM32F4/tim.cpp
SRC += hal/STM32F4/uart.cpp
SRC += hal/STM32F4/wdt.cpp

INC += src/hal/STM32F4
INC += src/hal/STM32F4/CMSIS/core-support
INC += src/hal/STM32F4/CMSIS/device-support/include

DEF += STM32F407xx
DEF += HSE_VALUE=8000000
DEF += ARM_MATH_CM4

LIBDIR += src/hal/STM32F4/CMSIS/lib
LIB += arm_cortexM4lf_math
LINKED_OBJ +=
