-include ../../../header.mk

SRC := dac.cpp \
	dma.cpp \
	exti.cpp \
	gpio.cpp \
	i2c.cpp \
	pwm.cpp \
	rcc.cpp \
	rtc.cpp \
	spi.cpp \
	systick.cpp \
	tim.cpp \
	uart.cpp \
	wdt.cpp

INC :=

DEF :=
C_CPP_FLAGS := -Wno-unused-variable
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../../footer.mk
