-include ../../header.mk

SRC := di/di.cpp \
	enc/enc.cpp \
	onewire/onewire.cpp \
	dht11/dht11.cpp \
	dht22/dht22.cpp \
	ds18b20/ds18b20.cpp \
	sd/sd.cpp \
	sd/sd_spi.cpp \
	singlewire/singlewire.cpp \
	hd44780/hd44780.cpp

INC :=
DEF :=
C_CPP_FLAGS :=
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../footer.mk
