-include ../../header.mk

SRC := di/di.cpp \
	enc/enc.cpp \
	1w/1w.cpp \
	ds18b20/ds18b20.cpp \
	sd/sd.cpp \
	sd/sd_spi.cpp \
	hd44780/hd44780.cpp

INC :=
DEF :=
C_CPP_FLAGS :=
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../footer.mk
